#!/bin/bash
echo "10-2.fdf"
./fdf test_maps/10-2.fdf
echo "10-70.fdf"
./fdf test_maps/10-70.fdf
echo "100-6.fdf"
./fdf test_maps/100-6.fdf
echo "20-60.fdf"
./fdf test_maps/20-60.fdf
echo "42.fdf"
./fdf test_maps/42.fdf
echo "50-4.fdf"
./fdf test_maps/50-4.fdf
echo "basictest.fdf"
./fdf test_maps/basictest.fdf
echo "elem-col.fdf"
./fdf test_maps/elem-col.fdf
echo "elem-fract.fdf"
./fdf test_maps/elem-fract.fdf
echo "elem.fdf"
./fdf test_maps/elem.fdf
echo "elem2.fdf"
./fdf test_maps/elem2.fdf
echo "julia.fdf"
./fdf test_maps/julia.fdf
echo "mars.fdf"
./fdf test_maps/mars.fdf
echo "n_lines"
./fdf test_maps/n_lines
echo "pentenegpos.fdf"
./fdf test_maps/pentenegpos.fdf
echo "plat.fdf"
./fdf test_maps/plat.fdf
echo "pnp_flat.fdf"
./fdf test_maps/pnp_flat.fdf
echo "pylone.fdf"
./fdf test_maps/pylone.fdf
echo "pyra.fdf"
./fdf test_maps/pyra.fdf
echo "pyramide.fdf"
./fdf test_maps/pyramide.fdf
echo "t1.fdf"
./fdf test_maps/t1.fdf
echo "t2.fdf"
./fdf test_maps/t2.fdf

